spring.application.name=portfolio-api
spring.datasource.url=jdbc:h2:file:./data/portfoliodb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.datasource.username=sa
spring.datasource.password=
server.port=${PORT:8080}